name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test

  build_android:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm ci

    - name: Build Android
      run: npx react-native build-android --mode release

  build_ios:
    needs: test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm ci

    - name: Install iOS dependencies
      run: |
        cd ios
        pod install

    - name: Build iOS
      run: |
        cd ios
        xcodebuild -workspace LISD.xcworkspace -scheme LISD -configuration Release -derivedDataPath build
